### ISSUE TITLE
Layer group "Amtliche Vermessung" cannot be loaded

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#58]
The complex layer group "Amtliche Vermessung" cannot be loaded currently:

Neither PG nor WMS version seems to work.

![image](https://user-images.githubusercontent.com/884476/69421051-51295800-0d20-11ea-8ff4-c6424e7ad9d5.png)

Python error message:

```
2019-11-22T12:01:36     WARNING    Traceback (most recent call last):
              File "C:/Users/bjsvwneu/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\solocator\core\solocator_filter.py", line 440, in 
              self.nam_fetch_feature.finished.connect(lambda response: self.parse_data_product_response(response, is_background, alternate_mode))
              File "C:/Users/bjsvwneu/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\solocator\core\solocator_filter.py", line 451, in parse_data_product_response
              LayerLoader(data, self.iface, is_background, alternate_mode)
              File "C:/Users/bjsvwneu/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\solocator\core\layer_loader.py", line 62, in __init__
              if force_wms(data, is_background):
              File "C:/Users/bjsvwneu/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\solocator\core\data_products.py", line 117, in force_wms
              if child.postgis_datasource is None:
             AttributeError: 'SoGroup' object has no attribute 'postgis_datasource'
```

**Comment by andreasneumann** [comment]
Same if you want to load the whole layer group "Richtplan"

![image](https://user-images.githubusercontent.com/884476/69421772-32c45c00-0d22-11ea-9725-bc78d2f80d5e.png)
